# Generated by Django 3.0.5 on 2020-04-18 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Article')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
